# Image de depart
FROM node 

WORKDIR /app

ENV PORT=3002

# copie de pacjage.json et package-lock.json
COPY package*.json ./

# Installation des dependances
RUN npm install 

COPY . .

EXPOSE ${PORT}

CMD ["node","app.js"]

# commande pour construire l'image
# docker build -t apptodo . --no-cache

# commande pour lancer un container avec cette image
# docker run -p 5000:3001 -d apptodo


